name             'site'
maintainer       'Kevin Miscia'
maintainer_email 'kmiscia@miscia.net'
license          'All rights reserved'
description      'Builds the server for miscia.net'
version          '0.1.0'