name             'site-ruby'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures site-ruby'
long_description 'Installs/Configures site-ruby'
version          '0.1.0'

depends 'build-essential'
#depends 'ruby_build'
depends 'rbenv'
